#ifndef SLAM_SLAM_CHANNELS_HPP
#define SLAM_SLAM_CHANNELS_HPP

#define SLAM_MAP_CHANNEL "SLAM_MAP"
#define SLAM_POSE_CHANNEL "SLAM_POSE"
#define SLAM_PARTICLES_CHANNEL "SLAM_PARTICLES"

#define SLAM_LIDAR_CHANNEL "SLAM_LIDAR"
#define SLAM_TRUE_POSE_CHANNEL "SLAM_TRUE_POSE"
#define SLAM_MAP_POSE_CHANNEL "SLAM_MAP_POSE"

#endif // SLAM_SLAM_CHANNELS_HPP
