/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __lidar_t_hpp__
#define __lidar_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>


class lidar_t
{
    public:
        int64_t    utime;

        /**
         * Measured range in meters
         * Measurement angle in radians
         * Measurement time was taken in usec
         * Measurement intensity -- unitless
         */
        int32_t    num_ranges;

        std::vector< float > ranges;

        /// [m]
        std::vector< float > thetas;

        /// [rad]
        std::vector< int64_t > times;

        /// [usec]
        std::vector< float > intensities;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lidar_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lidar_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lidar_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lidar_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lidar_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* lidar_t::getTypeName()
{
    return "lidar_t";
}

int lidar_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_ranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_ranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->thetas[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges > 0) {
        tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->times[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lidar_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_ranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_ranges) {
        this->ranges.resize(this->num_ranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges) {
        this->thetas.resize(this->num_ranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->thetas[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges) {
        this->times.resize(this->num_ranges);
        tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->times[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges) {
        this->intensities.resize(this->num_ranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lidar_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->num_ranges);
    enc_size += __float_encoded_array_size(NULL, this->num_ranges);
    enc_size += __int64_t_encoded_array_size(NULL, this->num_ranges);
    enc_size += __float_encoded_array_size(NULL, this->num_ranges);
    return enc_size;
}

uint64_t lidar_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xc4ee2dc3cd282b67LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
