// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _exploration_status_t_h
#define _exploration_status_t_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#define EXPLORATION_STATUS_T_STATE_INITIALIZING 0
#define EXPLORATION_STATUS_T_STATE_EXPLORING_MAP 1
#define EXPLORATION_STATUS_T_STATE_RETURNING_HOME 2
#define EXPLORATION_STATUS_T_STATE_COMPLETED_EXPLORATION 3
#define EXPLORATION_STATUS_T_STATE_FAILED_EXPLORATION 4
#define EXPLORATION_STATUS_T_STATUS_IN_PROGRESS 0
#define EXPLORATION_STATUS_T_STATUS_COMPLETE 1
#define EXPLORATION_STATUS_T_STATUS_FAILED 2

typedef struct _exploration_status_t exploration_status_t;
struct _exploration_status_t
{
    /**
     * utime is the time at which the message was generated.
     *
     */
    int64_t    utime;
    /**
     * team_number is the assigned team number of the robot sending the messages.
     *
     */
    int32_t    team_number;
    /**
     * state is the current exploration state as defined by the possible STATE_ values above. As exploration transitions
     * between states, it should always indicate when a state has been completed or failed in addition to when it is
     * in-progress.
     *
     */
    int8_t     state;
    /**
     * status is the current status of exploration within the current state. While working towards completing a task,
     * the status is STATUS_IN_PROGRESS. Once completed, a message with STATUS_COMPLETE must be sent to tell the scoring
     * program of the change.
     *
     */
    int8_t     status;
};

/**
 * Create a deep copy of a exploration_status_t.
 * When no longer needed, destroy it with exploration_status_t_destroy()
 */
exploration_status_t* exploration_status_t_copy(const exploration_status_t* to_copy);

/**
 * Destroy an instance of exploration_status_t created by exploration_status_t_copy()
 */
void exploration_status_t_destroy(exploration_status_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _exploration_status_t_subscription_t exploration_status_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * exploration_status_t is received.
 */
typedef void(*exploration_status_t_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const exploration_status_t *msg, void *userdata);

/**
 * Publish a message of type exploration_status_t using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int exploration_status_t_publish(lcm_t *lcm, const char *channel, const exploration_status_t *msg);

/**
 * Subscribe to messages of type exploration_status_t using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
exploration_status_t_subscription_t* exploration_status_t_subscribe(
    lcm_t *lcm, const char *channel, exploration_status_t_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by exploration_status_t_subscribe()
 */
int exploration_status_t_unsubscribe(lcm_t *lcm, exploration_status_t_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int exploration_status_t_subscription_set_queue_capacity(
    exploration_status_t_subscription_t* subs, int num_messages);

/**
 * Encode a message of type exploration_status_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to exploration_status_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int exploration_status_t_encode(void *buf, int offset, int maxlen, const exploration_status_t *p);

/**
 * Decode a message of type exploration_status_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with exploration_status_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int exploration_status_t_decode(const void *buf, int offset, int maxlen, exploration_status_t *msg);

/**
 * Release resources allocated by exploration_status_t_decode()
 * @return 0
 */
int exploration_status_t_decode_cleanup(exploration_status_t *p);

/**
 * Check how many bytes are required to encode a message of type exploration_status_t
 */
int exploration_status_t_encoded_size(const exploration_status_t *p);
size_t exploration_status_t_struct_size(void);
int exploration_status_t_num_fields(void);
int exploration_status_t_get_field(const exploration_status_t *p, int i, lcm_field_t *f);
const lcm_type_info_t *exploration_status_t_get_type_info(void);

// LCM support functions. Users should not call these
int64_t __exploration_status_t_get_hash(void);
uint64_t __exploration_status_t_hash_recursive(const __lcm_hash_ptr *p);
int __exploration_status_t_encode_array(
    void *buf, int offset, int maxlen, const exploration_status_t *p, int elements);
int __exploration_status_t_decode_array(
    const void *buf, int offset, int maxlen, exploration_status_t *p, int elements);
int __exploration_status_t_decode_array_cleanup(exploration_status_t *p, int elements);
int __exploration_status_t_encoded_array_size(const exploration_status_t *p, int elements);
int __exploration_status_t_clone_array(const exploration_status_t *p, exploration_status_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
