// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "exploration_status_t.h"

static int __exploration_status_t_hash_computed;
static uint64_t __exploration_status_t_hash;

uint64_t __exploration_status_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __exploration_status_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __exploration_status_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x46cc0600966c2be3LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __exploration_status_t_get_hash(void)
{
    if (!__exploration_status_t_hash_computed) {
        __exploration_status_t_hash = (int64_t)__exploration_status_t_hash_recursive(NULL);
        __exploration_status_t_hash_computed = 1;
    }

    return __exploration_status_t_hash;
}

int __exploration_status_t_encode_array(void *buf, int offset, int maxlen, const exploration_status_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].team_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int exploration_status_t_encode(void *buf, int offset, int maxlen, const exploration_status_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __exploration_status_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __exploration_status_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __exploration_status_t_encoded_array_size(const exploration_status_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int32_t_encoded_array_size(&(p[element].team_number), 1);

        size += __int8_t_encoded_array_size(&(p[element].state), 1);

        size += __int8_t_encoded_array_size(&(p[element].status), 1);

    }
    return size;
}

int exploration_status_t_encoded_size(const exploration_status_t *p)
{
    return 8 + __exploration_status_t_encoded_array_size(p, 1);
}

size_t exploration_status_t_struct_size(void)
{
    return sizeof(exploration_status_t);
}

int exploration_status_t_num_fields(void)
{
    return 4;
}

int exploration_status_t_get_field(const exploration_status_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= exploration_status_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 1: {
            f->name = "team_number";
            f->type = LCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void *) &p->team_number;
            return 0;
        }
        
        case 2: {
            f->name = "state";
            f->type = LCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void *) &p->state;
            return 0;
        }
        
        case 3: {
            f->name = "status";
            f->type = LCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void *) &p->status;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *exploration_status_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) exploration_status_t_encode;
        typeinfo.decode         = (lcm_decode_t) exploration_status_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) exploration_status_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) exploration_status_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  exploration_status_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) exploration_status_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) exploration_status_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __exploration_status_t_get_hash;
    }
    
    return &typeinfo;
}
int __exploration_status_t_decode_array(const void *buf, int offset, int maxlen, exploration_status_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].team_number), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __exploration_status_t_decode_array_cleanup(exploration_status_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int32_t_decode_array_cleanup(&(p[element].team_number), 1);

        __int8_t_decode_array_cleanup(&(p[element].state), 1);

        __int8_t_decode_array_cleanup(&(p[element].status), 1);

    }
    return 0;
}

int exploration_status_t_decode(const void *buf, int offset, int maxlen, exploration_status_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __exploration_status_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __exploration_status_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int exploration_status_t_decode_cleanup(exploration_status_t *p)
{
    return __exploration_status_t_decode_array_cleanup(p, 1);
}

int __exploration_status_t_clone_array(const exploration_status_t *p, exploration_status_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int32_t_clone_array(&(p[element].team_number), &(q[element].team_number), 1);

        __int8_t_clone_array(&(p[element].state), &(q[element].state), 1);

        __int8_t_clone_array(&(p[element].status), &(q[element].status), 1);

    }
    return 0;
}

exploration_status_t *exploration_status_t_copy(const exploration_status_t *p)
{
    exploration_status_t *q = (exploration_status_t*) malloc(sizeof(exploration_status_t));
    __exploration_status_t_clone_array(p, q, 1);
    return q;
}

void exploration_status_t_destroy(exploration_status_t *p)
{
    __exploration_status_t_decode_array_cleanup(p, 1);
    free(p);
}

int exploration_status_t_publish(lcm_t *lc, const char *channel, const exploration_status_t *p)
{
      int max_data_size = exploration_status_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = exploration_status_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _exploration_status_t_subscription_t {
    exploration_status_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void exploration_status_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    exploration_status_t p;
    memset(&p, 0, sizeof(exploration_status_t));
    status = exploration_status_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding exploration_status_t!!!\n", status);
        return;
    }

    exploration_status_t_subscription_t *h = (exploration_status_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    exploration_status_t_decode_cleanup (&p);
}

exploration_status_t_subscription_t* exploration_status_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    exploration_status_t_handler_t f, void *userdata)
{
    exploration_status_t_subscription_t *n = (exploration_status_t_subscription_t*)
                       malloc(sizeof(exploration_status_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 exploration_status_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg exploration_status_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int exploration_status_t_subscription_set_queue_capacity (exploration_status_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int exploration_status_t_unsubscribe(lcm_t *lcm, exploration_status_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe exploration_status_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

