// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "wifi_data_t.h"

static int __wifi_data_t_hash_computed;
static uint64_t __wifi_data_t_hash;

uint64_t __wifi_data_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __wifi_data_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __wifi_data_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x24a240b71ffcb820LL
         + __int64_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __wifi_data_t_get_hash(void)
{
    if (!__wifi_data_t_hash_computed) {
        __wifi_data_t_hash = (int64_t)__wifi_data_t_hash_recursive(NULL);
        __wifi_data_t_hash_computed = 1;
    }

    return __wifi_data_t_hash;
}

int __wifi_data_t_encode_array(void *buf, int offset, int maxlen, const wifi_data_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mac_address), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ssid), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].strength), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int wifi_data_t_encode(void *buf, int offset, int maxlen, const wifi_data_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __wifi_data_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __wifi_data_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __wifi_data_t_encoded_array_size(const wifi_data_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __string_encoded_array_size(&(p[element].mac_address), 1);

        size += __string_encoded_array_size(&(p[element].ssid), 1);

        size += __float_encoded_array_size(&(p[element].strength), 1);

    }
    return size;
}

int wifi_data_t_encoded_size(const wifi_data_t *p)
{
    return 8 + __wifi_data_t_encoded_array_size(p, 1);
}

size_t wifi_data_t_struct_size(void)
{
    return sizeof(wifi_data_t);
}

int wifi_data_t_num_fields(void)
{
    return 4;
}

int wifi_data_t_get_field(const wifi_data_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= wifi_data_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "timestamp";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->timestamp;
            return 0;
        }
        
        case 1: {
            f->name = "mac_address";
            f->type = LCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void *) &p->mac_address;
            return 0;
        }
        
        case 2: {
            f->name = "ssid";
            f->type = LCM_FIELD_STRING;
            f->typestr = "string";
            f->num_dim = 0;
            f->data = (void *) &p->ssid;
            return 0;
        }
        
        case 3: {
            f->name = "strength";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->strength;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *wifi_data_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) wifi_data_t_encode;
        typeinfo.decode         = (lcm_decode_t) wifi_data_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) wifi_data_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) wifi_data_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  wifi_data_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) wifi_data_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) wifi_data_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __wifi_data_t_get_hash;
    }
    
    return &typeinfo;
}
int __wifi_data_t_decode_array(const void *buf, int offset, int maxlen, wifi_data_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mac_address), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ssid), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].strength), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __wifi_data_t_decode_array_cleanup(wifi_data_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __string_decode_array_cleanup(&(p[element].mac_address), 1);

        __string_decode_array_cleanup(&(p[element].ssid), 1);

        __float_decode_array_cleanup(&(p[element].strength), 1);

    }
    return 0;
}

int wifi_data_t_decode(const void *buf, int offset, int maxlen, wifi_data_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __wifi_data_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __wifi_data_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int wifi_data_t_decode_cleanup(wifi_data_t *p)
{
    return __wifi_data_t_decode_array_cleanup(p, 1);
}

int __wifi_data_t_clone_array(const wifi_data_t *p, wifi_data_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __string_clone_array(&(p[element].mac_address), &(q[element].mac_address), 1);

        __string_clone_array(&(p[element].ssid), &(q[element].ssid), 1);

        __float_clone_array(&(p[element].strength), &(q[element].strength), 1);

    }
    return 0;
}

wifi_data_t *wifi_data_t_copy(const wifi_data_t *p)
{
    wifi_data_t *q = (wifi_data_t*) malloc(sizeof(wifi_data_t));
    __wifi_data_t_clone_array(p, q, 1);
    return q;
}

void wifi_data_t_destroy(wifi_data_t *p)
{
    __wifi_data_t_decode_array_cleanup(p, 1);
    free(p);
}

int wifi_data_t_publish(lcm_t *lc, const char *channel, const wifi_data_t *p)
{
      int max_data_size = wifi_data_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = wifi_data_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _wifi_data_t_subscription_t {
    wifi_data_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void wifi_data_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    wifi_data_t p;
    memset(&p, 0, sizeof(wifi_data_t));
    status = wifi_data_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding wifi_data_t!!!\n", status);
        return;
    }

    wifi_data_t_subscription_t *h = (wifi_data_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    wifi_data_t_decode_cleanup (&p);
}

wifi_data_t_subscription_t* wifi_data_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    wifi_data_t_handler_t f, void *userdata)
{
    wifi_data_t_subscription_t *n = (wifi_data_t_subscription_t*)
                       malloc(sizeof(wifi_data_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 wifi_data_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg wifi_data_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int wifi_data_t_subscription_set_queue_capacity (wifi_data_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int wifi_data_t_unsubscribe(lcm_t *lcm, wifi_data_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe wifi_data_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

